package com.tuitionmanager.domain;

public enum ExpenseCategory {
  ROOM_RENT,
  ELECTRICITY_BILL,
  INTERNET_BILL,
  BOOKS,
  STATIONERY,
  WHITEBOARD_AND_MARKERS,
  PRINTER_EXPENSES,
  STUDY_MATERIALS,
  SNACKS_AND_WATER,
  TRANSPORTATION,
  MARKETING_FLYERS,
  MISCELLANEOUS
}
